[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "ds-test=lib/forge-std/lib/ds-test/src",
    "forge-std=lib/forge-std/src"
]
ffi = true
